# /etc/apache2/conf-available/ttyd.conf

<IfModule mod_proxy.c>
	ProxyRequests Off
	ProxyPreserveHost On

	ProxyPass /ttyd/ws ws://127.0.0.1:7681/ws
	ProxyPassReverse /ttyd/ws ws://127.0.0.1:7681/ws

	ProxyPass /ttyd http://127.0.0.1:7681 keepalive=on
	ProxyPassReverse /ttyd http://127.0.0.1:7681

	<IfFile /etc/ttyd/apache2-auth.conf>
		<Location /ttyd>
			Include /etc/ttyd/apache2-auth.conf
		</Location>
	</IfFile>
</IfModule>
