github.com:
    users:
        KarotsSugarpie:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: KarotsSugarpie
