github.com:
    users:
        KarotsSugarpie:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: KarotsSugarpie
