sunshine_name = PinCabOS-NvFBC-Probe
min_log_level = debug
system_tray = disabled

controller = disabled
keyboard = disabled
mouse = disabled
stream_audio = disabled

capture = nvfbc
encoder = nvenc
nvenc_preset = 1
nvenc_twopass = disabled
channels = 1

upnp = disabled
address_family = ipv4
bind_address = 127.0.0.1
port = 48989
origin_web_ui_allowed = pc

credentials_file = /opt/pincabos/apps/sunshine-stream-test/2026-07-03-163547/nvfbc-probe-2026-07-03-163710/credentials.json
file_state = /opt/pincabos/apps/sunshine-stream-test/2026-07-03-163547/nvfbc-probe-2026-07-03-163710/state.json
file_apps = /opt/pincabos/apps/sunshine-stream-test/2026-07-03-163547/nvfbc-probe-2026-07-03-163710/apps.json
log_path = /opt/pincabos/apps/sunshine-stream-test/2026-07-03-163547/nvfbc-probe-2026-07-03-163710/sunshine.log
pkey = /opt/pincabos/apps/sunshine-stream-test/2026-07-03-163547/nvfbc-probe-2026-07-03-163710/cakey.pem
cert = /opt/pincabos/apps/sunshine-stream-test/2026-07-03-163547/nvfbc-probe-2026-07-03-163710/cacert.pem
