#!/usr/bin/env bash
set -Eeuo pipefail

ISO="${1:-/opt/pincabos/script/iso.sh}"
STAMP="$(date +%Y%m%d-%H%M%S)"
BACKUP="${ISO}.before-orientation-rootadmin-${STAMP}"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

echo "==============================================================="
echo " PINCABOS V8.1G — ORIENTATION + PINBALL ROOT ADMIN"
echo "==============================================================="
echo "Source : $ISO"

if [ ! -f "$ISO" ]; then
  echo "ERREUR: fichier introuvable: $ISO"
  exit 1
fi

if ! bash -n "$ISO"; then
  echo "ERREUR: iso.sh contient deja une erreur de syntaxe. Aucun changement."
  exit 1
fi

echo
echo "=== 1) Sauvegarde ==="
cp -a --preserve=all "$ISO" "$BACKUP"
echo "GO [OK] $BACKUP"

cp -a --preserve=all "$ISO" "$TMP"

echo
echo "=== 2) Injection ciblee ==="
python3 - "$TMP" <<'PY'
from pathlib import Path
import sys

p = Path(sys.argv[1])
s = p.read_text(encoding="utf-8")
changed = []


def once_replace(old: str, new: str, label: str):
    global s
    n = s.count(old)
    if n != 1:
        raise SystemExit(f"ERREUR: ancre {label!r}: {n} occurrence(s), attendu 1")
    s = s.replace(old, new, 1)
    changed.append(label)

# ------------------------------------------------------------------
# 1) Orientation dans le live installer deja data-driven.
# ------------------------------------------------------------------
if "PINCABOS_ORIENTATION_INSTALLER_V1" not in s:
    once_replace(
        'REG_TIMEZONE="America/Montreal"\n',
        'REG_TIMEZONE="America/Montreal"\n'
        'REG_FBROTATE=0\n'
        'REG_ORIENT_LABEL="Landscape (no rotation)"\n'
        '# PINCABOS_ORIENTATION_INSTALLER_V1\n',
        "variables orientation",
    )

    orient_menu = r'''        REG_TIMEZONE="$PCO_SELECTED"

        # Screen orientation for cabinet display / boot splash.
        echo
        pco_hr
        echo " Screen orientation"
        pco_hr
        echo
        echo "  [1] Landscape (no rotation)"
        echo "  [2] Portrait — 90 degrees clockwise"
        echo "  [3] Portrait — 90 degrees counter-clockwise"
        echo "  [4] Upside down — 180 degrees"
        echo

        while true; do
            pco_prompt "Choice: "
            read -r CHOICE
            case "$CHOICE" in
                1) REG_FBROTATE=0; REG_ORIENT_LABEL="Landscape"; break ;;
                2) REG_FBROTATE=1; REG_ORIENT_LABEL="Portrait 90 clockwise"; break ;;
                3) REG_FBROTATE=3; REG_ORIENT_LABEL="Portrait 90 counter-clockwise"; break ;;
                4) REG_FBROTATE=2; REG_ORIENT_LABEL="Upside down 180"; break ;;
                *) pco_warn "Invalid choice." ;;
            esac
        done
'''
    once_replace(
        '        REG_TIMEZONE="$PCO_SELECTED"\n',
        orient_menu,
        "menu orientation",
    )

    once_replace(
        '        echo " Timezone : $REG_TIMEZONE"\n',
        '        echo " Timezone : $REG_TIMEZONE"\n'
        '        echo " Screen   : $REG_ORIENT_LABEL"\n',
        "recap orientation",
    )

    orientation_function = r'''
apply_target_orientation() {
    echo
    pco_step "Applying screen orientation to installed PinCabOS"

    local N="${REG_FBROTATE:-0}"
    local GRUBF="$TARGET/etc/default/grub"

    case "$N" in
        0|1|2|3) ;;
        *) pco_error "Invalid fbcon rotation value: $N"; return 1 ;;
    esac

    # 1) Console/kernel rotation. Remove any previous value first.
    if [ -f "$GRUBF" ]; then
        sed -i -E 's/[[:space:]]*fbcon=rotate:[0-3]//g' "$GRUBF"

        if [ "$N" != "0" ]; then
            if grep -q '^GRUB_CMDLINE_LINUX_DEFAULT=' "$GRUBF"; then
                sed -i -E \
                    "s/^(GRUB_CMDLINE_LINUX_DEFAULT=\")(.*)(\")[[:space:]]*$/\\1\\2 fbcon=rotate:$N\\3/" \
                    "$GRUBF"
            else
                printf 'GRUB_CMDLINE_LINUX_DEFAULT="fbcon=rotate:%s"\n' "$N" >> "$GRUBF"
            fi
        fi
    else
        pco_warn "target /etc/default/grub missing — console rotation skipped"
    fi

    # 2) Rotation-aware PinCabOS Plymouth splash.
    local THEME="$TARGET/usr/share/plymouth/themes/pincabos/pincabos.script"
    if [ -f "$THEME" ] && [ "$N" != "0" ]; then
        local DEG=0
        [ "$N" = "1" ] && DEG=90
        [ "$N" = "2" ] && DEG=180
        [ "$N" = "3" ] && DEG=270

        [ -f "$THEME.pcosorig" ] || cp "$THEME" "$THEME.pcosorig"

        cat > "$THEME" <<'PLYSCRIPT'
# PINCABOS rotation-aware splash (generated by installer)
rot = __ROT_DEG__;
sw = Window.GetWidth();
sh = Window.GetHeight();
PI = 3.14159265358979;
rad = rot * PI / 180;
if (rot == 90 || rot == 270) { lw = sh; lh = sw; } else { lw = sw; lh = sh; }

bg = Image("pincabos.png").Scale(lw, lh);
if (rot != 0) bg = bg.Rotate(rad);
bgs = Sprite(bg);
bgs.SetX((sw - bg.GetWidth()) / 2);
bgs.SetY((sh - bg.GetHeight()) / 2);
bgs.SetZ(-100);

bar_width = lw * 0.193;
bar_height = 6;
bar_lx = (lw - bar_width) / 2;
bar_ly = lh * 0.728;
bcx = bar_lx + bar_width / 2;
bcy = bar_ly + bar_height / 2;

if (rot == 0)   { pcx = bcx;      pcy = bcy;      }
if (rot == 180) { pcx = sw - bcx; pcy = sh - bcy; }
if (rot == 90)  { pcx = sw - bcy; pcy = bcx;      }
if (rot == 270) { pcx = bcy;      pcy = sh - bcx; }

box_img = Image("progress_box.png").Scale(bar_width, bar_height);
if (rot != 0) box_img = box_img.Rotate(rad);
box_sprite = Sprite(box_img);
box_sprite.SetX(pcx - box_img.GetWidth() / 2);
box_sprite.SetY(pcy - box_img.GetHeight() / 2);
box_sprite.SetZ(10);

bar_img0 = Image("progress_bar.png");
bar_sprite = Sprite();
bar_sprite.SetZ(11);

fun boot_progress_callback(duration, progress) {
    if (progress < 0) progress = 0;
    if (progress > 1) progress = 1;
    cw = bar_width * progress;
    if (cw < 1) cw = 1;
    img = bar_img0.Scale(cw, bar_height);
    if (rot != 0) img = img.Rotate(rad);
    bar_sprite.SetImage(img);
    bar_sprite.SetX(pcx - img.GetWidth() / 2);
    bar_sprite.SetY(pcy - img.GetHeight() / 2);
}
Plymouth.SetBootProgressFunction(boot_progress_callback);
PLYSCRIPT
        sed -i "s/__ROT_DEG__/$DEG/" "$THEME"
        pco_go "Plymouth splash rotated: $DEG degrees"
    fi

    # 3) Persistent PinCabOS record.
    mkdir -p "$TARGET/etc/pincabos"
    printf 'PINCABOS_FBCON_ROTATE="%s"\nPINCABOS_ORIENT_LABEL="%s"\n' \
        "$N" "${REG_ORIENT_LABEL:-Landscape}" \
        > "$TARGET/etc/pincabos/orientation.conf"
    chmod 0644 "$TARGET/etc/pincabos/orientation.conf"

    pco_go "Orientation installed: ${REG_ORIENT_LABEL:-Landscape}"
}

'''
    once_replace(
        '\napply_target_regional() {\n',
        '\n' + orientation_function + 'apply_target_regional() {\n',
        "fonction apply_target_orientation",
    )

    once_replace(
        '  apply_target_regional\n',
        '  apply_target_regional\n'
        '  apply_target_orientation\n\n'
        '  test -f "$TARGET/etc/pincabos/orientation.conf"\n',
        "appel apply_target_orientation",
    )
else:
    print("INFO: orientation deja integree — aucune duplication")

# ------------------------------------------------------------------
# 2) pinball UID/GID 1000 + sudo root NOPASSWD + Polkit complet.
#    Injection dans le payload helper, juste apres sa validation UID/GID.
# ------------------------------------------------------------------
if "PINCABOS_PINBALL_ROOT_ADMIN_POLICY_V1" not in s:
    admin_block = r'''

# PINCABOS_PINBALL_ROOT_ADMIN_POLICY_V1
echo
echo "=== 2c) PINCABOS POLICY: pinball UID 1000 + full local administration ==="

PCOS_TARGET_PB_UID="$(awk -F: '$1=="pinball"{print $3; exit}' "$TARGET/etc/passwd" 2>/dev/null || true)"
PCOS_TARGET_PB_GID="$(awk -F: '$1=="pinball"{print $4; exit}' "$TARGET/etc/passwd" 2>/dev/null || true)"

if [ "$PCOS_TARGET_PB_UID" != "1000" ] || [ "$PCOS_TARGET_PB_GID" != "1000" ]; then
  echo "ERROR: PinCabOS invariant failed: pinball must be uid=1000 gid=1000"
  echo "       detected uid=${PCOS_TARGET_PB_UID:-missing} gid=${PCOS_TARGET_PB_GID:-missing}"
  exit 1
fi

if [ ! -x "$TARGET/usr/bin/sudo" ]; then
  echo "ERROR: sudo missing from target rootfs"
  exit 1
fi

# Full root via sudo without password, while keeping the interactive account UID 1000.
install -d -m 0750 "$TARGET/etc/sudoers.d"
cat > "$TARGET/etc/sudoers.d/99-pincabos-pinball-root" <<'SUDOEOF'
# PinCabOS dedicated cabinet account — intentional full local administration
pinball ALL=(ALL:ALL) NOPASSWD: ALL
SUDOEOF
chmod 0440 "$TARGET/etc/sudoers.d/99-pincabos-pinball-root"

if [ -x "$TARGET/usr/sbin/visudo" ]; then
  chroot "$TARGET" /usr/sbin/visudo -cf /etc/sudoers.d/99-pincabos-pinball-root
fi

# Keep standard sudo group membership too.
if [ -x "$TARGET/usr/sbin/usermod" ] && grep -q '^sudo:' "$TARGET/etc/group"; then
  chroot "$TARGET" /usr/sbin/usermod -aG sudo pinball
fi

# Full local Polkit authorization for the dedicated cabinet account.
install -d -m 0755 "$TARGET/etc/polkit-1/rules.d"
cat > "$TARGET/etc/polkit-1/rules.d/49-pincabos-pinball-root.rules" <<'POLKITEOF'
// PinCabOS dedicated cabinet account — intentional full local administration
polkit.addRule(function(action, subject) {
    if (subject.user == "pinball") {
        return polkit.Result.YES;
    }
});
POLKITEOF
chmod 0644 "$TARGET/etc/polkit-1/rules.d/49-pincabos-pinball-root.rules"

test -s "$TARGET/etc/sudoers.d/99-pincabos-pinball-root"
test -s "$TARGET/etc/polkit-1/rules.d/49-pincabos-pinball-root.rules"

echo "GO [OK] target pinball uid=1000 gid=1000"
echo "GO [OK] sudo NOPASSWD: ALL installed"
echo "GO [OK] unrestricted local Polkit rule installed"
'''
    marker = 'echo "GO [√] Target pinball identity validated."\n'
    once_replace(marker, marker + admin_block, "politique root admin pinball")
else:
    print("INFO: politique root-admin deja integree — aucune duplication")

p.write_text(s, encoding="utf-8")
print("GO [OK] injections:", ", ".join(changed) if changed else "aucune (deja present)")
PY

echo
echo "=== 3) Validation syntaxique AVANT remplacement ==="
if ! bash -n "$TMP"; then
  echo "ERREUR: la version modifiee ne passe pas bash -n."
  echo "AUCUNE modification appliquee a $ISO"
  exit 1
fi
echo "GO [OK] bash -n version modifiee"

echo
echo "=== 4) Installation de la nouvelle source ==="
# Preserve the original inode/ACL/owner/mode by replacing contents only.
cat "$TMP" > "$ISO"

if ! bash -n "$ISO"; then
  echo "ERREUR critique apres ecriture — restauration automatique"
  cat "$BACKUP" > "$ISO"
  bash -n "$ISO" || true
  exit 1
fi

echo "GO [OK] iso.sh mis a jour"

echo
echo "=== 5) Audit des marqueurs ==="
grep -n -E \
  'PINCABOS_ORIENTATION_INSTALLER_V1|REG_FBROTATE|REG_ORIENT_LABEL|apply_target_orientation|orientation\.conf|PINCABOS_PINBALL_ROOT_ADMIN_POLICY_V1|99-pincabos-pinball-root|49-pincabos-pinball-root|NOPASSWD: ALL|polkit\.Result\.YES' \
  "$ISO" || true

echo
echo "=== 6) Controle des occurrences ==="
for token in \
  PINCABOS_ORIENTATION_INSTALLER_V1 \
  'apply_target_orientation()' \
  PINCABOS_PINBALL_ROOT_ADMIN_POLICY_V1 \
  '99-pincabos-pinball-root' \
  '49-pincabos-pinball-root.rules'
do
  count="$(grep -F -c "$token" "$ISO" || true)"
  printf '%-48s : %s\n' "$token" "$count"
done

echo
echo "=== 7) SHA256 ==="
sha256sum "$BACKUP" "$ISO"

echo
echo "==============================================================="
echo " GO [OK] SOURCE ISO.SH PRETE"
echo " Backup : $BACKUP"
echo "==============================================================="
echo "Ne lance pas encore la reconstruction ISO; valide d'abord la sortie ci-dessus."
