# PinCabOS Hybrid Launcher runtime
#
# Runtime du launcher
d /run/pincabos-hybrid-launcher 0700 pinball pinball -
f /run/pincabos-hybrid-launcher/launcher.lock 0600 pinball pinball -

# Logs partagés.
#
# Le bit setgid garantit que même un fichier créé par root
# hérite du groupe pinball.
d /var/log/pincabos-hybrid-launcher 2775 pinball pinball -

# Le fichier est explicitement créé et normalisé.
f /var/log/pincabos-hybrid-launcher/launcher.log 0664 pinball pinball -
z /var/log/pincabos-hybrid-launcher/launcher.log 0664 pinball pinball -
