# PINCABOS_SMART_BATCH_TMPDIR_FIX_V34
#
# tempfile / Werkzeug / Waitress / worker
d /var/tmp/pincabos-smart-import 0750 pinball pinball -

# PINCABOS_BATCH_SHARED_DIR_OWNER_V3
d /var/lib/pincabos/batch-live-import 2770 pinball pinball -
d /var/lib/pincabos/batch-live-import/uploads 2770 pinball pinball -
