[Seat:*]
greeter-session=lightdm-gtk-greeter
user-session=pincabos-openbox
autologin-user=pinball
autologin-user-timeout=0
autologin-session=pincabos-openbox
greeter-hide-users=true
greeter-show-manual-login=false
allow-guest=false
